package com.disenkoart.howlongi.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.disenkoart.howlongi.database.Gradients;
import com.disenkoart.howlongi.database.Timers;

import com.disenkoart.howlongi.database.GradientsDao;
import com.disenkoart.howlongi.database.TimersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gradientsDaoConfig;
    private final DaoConfig timersDaoConfig;

    private final GradientsDao gradientsDao;
    private final TimersDao timersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gradientsDaoConfig = daoConfigMap.get(GradientsDao.class).clone();
        gradientsDaoConfig.initIdentityScope(type);

        timersDaoConfig = daoConfigMap.get(TimersDao.class).clone();
        timersDaoConfig.initIdentityScope(type);

        gradientsDao = new GradientsDao(gradientsDaoConfig, this);
        timersDao = new TimersDao(timersDaoConfig, this);

        registerDao(Gradients.class, gradientsDao);
        registerDao(Timers.class, timersDao);
    }
    
    public void clear() {
        gradientsDaoConfig.clearIdentityScope();
        timersDaoConfig.clearIdentityScope();
    }

    public GradientsDao getGradientsDao() {
        return gradientsDao;
    }

    public TimersDao getTimersDao() {
        return timersDao;
    }

}
