package com.disenkoart.howlongi.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.disenkoart.howlongi.database.Gradient;
import com.disenkoart.howlongi.database.Timer;

import com.disenkoart.howlongi.database.GradientDao;
import com.disenkoart.howlongi.database.TimerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gradientDaoConfig;
    private final DaoConfig timerDaoConfig;

    private final GradientDao gradientDao;
    private final TimerDao timerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gradientDaoConfig = daoConfigMap.get(GradientDao.class).clone();
        gradientDaoConfig.initIdentityScope(type);

        timerDaoConfig = daoConfigMap.get(TimerDao.class).clone();
        timerDaoConfig.initIdentityScope(type);

        gradientDao = new GradientDao(gradientDaoConfig, this);
        timerDao = new TimerDao(timerDaoConfig, this);

        registerDao(Gradient.class, gradientDao);
        registerDao(Timer.class, timerDao);
    }
    
    public void clear() {
        gradientDaoConfig.clearIdentityScope();
        timerDaoConfig.clearIdentityScope();
    }

    public GradientDao getGradientDao() {
        return gradientDao;
    }

    public TimerDao getTimerDao() {
        return timerDao;
    }

}
