package com.disenkoart.howlongi.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRADIENTS".
*/
public class GradientsDao extends AbstractDao<Gradients, Long> {

    public static final String TABLENAME = "GRADIENTS";

    /**
     * Properties of entity Gradients.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property StartColor = new Property(1, int.class, "startColor", false, "START_COLOR");
        public final static Property EndColor = new Property(2, int.class, "endColor", false, "END_COLOR");
    }


    public GradientsDao(DaoConfig config) {
        super(config);
    }
    
    public GradientsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GRADIENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"START_COLOR\" INTEGER NOT NULL ," + // 1: startColor
                "\"END_COLOR\" INTEGER NOT NULL );"); // 2: endColor
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GRADIENTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Gradients entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getStartColor());
        stmt.bindLong(3, entity.getEndColor());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Gradients entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getStartColor());
        stmt.bindLong(3, entity.getEndColor());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Gradients readEntity(Cursor cursor, int offset) {
        Gradients entity = new Gradients( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // startColor
            cursor.getInt(offset + 2) // endColor
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Gradients entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setStartColor(cursor.getInt(offset + 1));
        entity.setEndColor(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Gradients entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Gradients entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Gradients entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
