package com.disenkoart.howlongi.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIMERS".
*/
public class TimersDao extends AbstractDao<Timers, Long> {

    public static final String TABLENAME = "TIMERS";

    /**
     * Properties of entity Timers.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property HliString = new Property(1, String.class, "hliString", false, "HLI_STRING");
        public final static Property StartDateTime = new Property(2, int.class, "startDateTime", false, "START_DATE_TIME");
        public final static Property IsArchived = new Property(3, int.class, "isArchived", false, "IS_ARCHIVED");
        public final static Property GradientId = new Property(4, long.class, "gradientId", false, "GRADIENT_ID");
    }

    private DaoSession daoSession;


    public TimersDao(DaoConfig config) {
        super(config);
    }
    
    public TimersDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TIMERS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"HLI_STRING\" TEXT NOT NULL ," + // 1: hliString
                "\"START_DATE_TIME\" INTEGER NOT NULL ," + // 2: startDateTime
                "\"IS_ARCHIVED\" INTEGER NOT NULL ," + // 3: isArchived
                "\"GRADIENT_ID\" INTEGER NOT NULL );"); // 4: gradientId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TIMERS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Timers entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getHliString());
        stmt.bindLong(3, entity.getStartDateTime());
        stmt.bindLong(4, entity.getIsArchived());
        stmt.bindLong(5, entity.getGradientId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Timers entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getHliString());
        stmt.bindLong(3, entity.getStartDateTime());
        stmt.bindLong(4, entity.getIsArchived());
        stmt.bindLong(5, entity.getGradientId());
    }

    @Override
    protected final void attachEntity(Timers entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Timers readEntity(Cursor cursor, int offset) {
        Timers entity = new Timers( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // hliString
            cursor.getInt(offset + 2), // startDateTime
            cursor.getInt(offset + 3), // isArchived
            cursor.getLong(offset + 4) // gradientId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Timers entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setHliString(cursor.getString(offset + 1));
        entity.setStartDateTime(cursor.getInt(offset + 2));
        entity.setIsArchived(cursor.getInt(offset + 3));
        entity.setGradientId(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Timers entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Timers entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Timers entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGradientsDao().getAllColumns());
            builder.append(" FROM TIMERS T");
            builder.append(" LEFT JOIN GRADIENTS T0 ON T.\"GRADIENT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Timers loadCurrentDeep(Cursor cursor, boolean lock) {
        Timers entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Gradients gradients = loadCurrentOther(daoSession.getGradientsDao(), cursor, offset);
         if(gradients != null) {
            entity.setGradients(gradients);
        }

        return entity;    
    }

    public Timers loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Timers> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Timers> list = new ArrayList<Timers>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Timers> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Timers> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
